#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 2 ]]; then
    echo "Usage: run_sensitivity_regression_check.sh <binary> <case_file>" >&2
    exit 2
fi

binary="$1"
case_file="$2"
case_name="$(basename "$case_file")"

# This suite runs realistic (~1000-timestep) forward+adjoint solves per
# perturbation and is not meant to gate every PR. It is opt-in: unset (or
# empty) NEKO_TOP_RUN_SENSITIVITY_REGRESSION means "skip", matching how
# run_valgrind_check.sh skips when the `valgrind` tool itself is absent, but
# here the gate is an explicit choice rather than a tool-availability check.
if [[ -z "${NEKO_TOP_RUN_SENSITIVITY_REGRESSION:-}" ]]; then
    echo "Skipping sensitivity regression test: set" \
        "NEKO_TOP_RUN_SENSITIVITY_REGRESSION=1 to opt in (this lane is not" \
        "part of the default/PR-blocking test budget)."
    exit 77
fi

if [[ ! -x "$binary" ]]; then
    echo "Executable not found or not executable: $binary" >&2
    exit 2
fi

if [[ ! -f "$case_file" ]]; then
    echo "Required case file not found: $case_file" >&2
    exit 2
fi

cp -f "$case_file" "$case_name"

if [[ "$case_name" == "scalar_mixing.case" ]]; then
    # scalar_mixing needs a real outlet split into y-quarters, so its box
    # must be non-periodic in y -- unlike every other case here, which
    # shares the periodic-y box below. It also needs a much finer mesh:
    # at Pe=200 (advection-dominated by design, see the case file's own
    # header comment for why that Pe was chosen), the cell Peclet number
    # (Pe * minimum nodal spacing) must stay below ~2 to avoid the
    # oscillatory/unstable regime, which this resolution (P=5,
    # nx x ny = 26 x 13) achieves with a measured cell Peclet of ~1.8 --
    # see the case file's own header comment for the derivation. Generated
    # into its own subdirectory: genmeshbox always writes a hardcoded
    # 'box.nmsh', so this cannot share a directory with the periodic-y box
    # below without a collision, and the two boxes are geometrically
    # different (non-periodic-y vs periodic-y) so could never be shared
    # even if the name collision were solved.
    sm_nx="${NEKO_TOP_SCALAR_MIXING_MESH_NX:-26}"
    sm_ny="${NEKO_TOP_SCALAR_MIXING_MESH_NY:-13}"
    sm_z=$(python3 -c "print(2.0 / ${sm_nx})")
    if [[ ! -f scalar_mixing_mesh/box.nmsh ]]; then
        echo "Generating scalar_mixing mesh: ${sm_nx} ${sm_ny} 1"
        mkdir -p scalar_mixing_mesh
        (cd scalar_mixing_mesh && genmeshbox 0 2 0 1 0 "$sm_z" \
            "$sm_nx" "$sm_ny" 1 .false. .false. .true.)
    fi
else
    mesh_n="${NEKO_TOP_SENSITIVITY_MESH_N:-8}"
    nx=$((mesh_n * 2))
    ny=$mesh_n
    nz=1
    z=$(python3 -c "print(1.0 / ${mesh_n})")

    # Reuse a mesh already generated by an earlier case in this same
    # (locked) working directory, to avoid regenerating it once per case.
    if [[ ! -f box.nmsh ]]; then
        echo "Generating mesh: ${nx} ${ny} ${nz}"
        genmeshbox 0 2 0 1 0 "$z" "$nx" "$ny" "$nz" .false. .true. .true.
    fi
fi

ranks="${NEKO_TOP_SENSITIVITY_RANKS:-2}"
export NEKO_LOG_FILE="neko_${case_name%.*}.log"

# The FD-vs-analytic tolerance assertion happens inside the driver itself
# (shared `sensitivity` module, see tests/unit/sensitivity/sensitivity.f90) —
# a non-zero exit here means the finite-difference check genuinely failed,
# not just that something crashed.
mpirun -n "$ranks" "$binary" "$case_name"

echo "Sensitivity regression check passed for ${case_name}."
